name: 'Setup Java'
description: 'Setup Java 25 with Zulu distribution and Gradle'

runs:
  using: 'composite'
  steps:
    - name: Set up Java
      uses: actions/setup-java@v4.5.0
      with:
        java-version: '25'
        distribution: "zulu"
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
