name: Release

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup git
        run: |
          git config --global user.name atdi
          git config --global user.email aurel.avramescu@gmail.com
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Release
        run: ./gradlew release -Prelease.useAutomaticVersion=true -Prelease.releaseVersion=0.1.0 -Prelease.newVersion=0.1.1-SNAPSHOT
